### PR TITLE
Allow working with authentication

### PR DESCRIPTION
**Pull request by jBouyoud**
This is a basic support of authentication that allows to run instl on private repositories

### CODE REVIEW

**Comment by jBouyoud** [comment]
@MarvinJWendt How can I help to get this Pr merged ?

**Comment by MarvinJWendt** [comment]
Hi @jBouyoud, it looks like this only works on Linux based systems. Could you please also include this for PowerShell? Thanks!

**Comment by jBouyoud** [comment]
@MarvinJWendt Hard for me since I haven't any PowerShell on my hand 😭

**Comment by jBouyoud** [comment]
@MarvinJWendt I try something 🤞  but this is not tested

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for contributing 🚀

**Comment by MarvinJWendt** [comment]
Hi @jBouyoud, sorry that it took so long. I accidentally marked the notification of this issue as "done".

**Comment by MarvinJWendt** [comment]
The deployment is currently running, you can expect it to be live in the next 10-15 minutes.

**Pull request merged**
